Add opreator ChangeDateFormatToStartToEnd
qcri/tasrif pull request #26
Opened 2022-01-24 01:44 UTC by abalhomaid

part of intern refactored code

2022-01-26 05:44 UTC, uabbas commented on tasrif/processing_pipeline/custom/change_date_format_to_start_to_end.py
> +    >>> from tasrif.processing_pipeline.custom import ChangeDateFormatToStartToEnd
I think the name of the class `ChangeDateFormatToStartToEnd` is a bit misleading. It is actually aggregating the rows in a special way such that the start and end time per record is known. `AggregateActivityDatesOperator` or something similar would be more appropriate.

2022-01-26 05:44 UTC, uabbas commented on tasrif/processing_pipeline/custom/change_date_format_to_start_to_end.py
> +                 aggregation_definition=None,
Do we really need aggregation_defintition toe be passed here?

2022-01-26 05:45 UTC, uabbas commented on tasrif/processing_pipeline/custom/change_date_format_to_start_to_end.py
> +        """Creates a new instance of EncodeCyclicalFeaturesOperator
class name is not `EncodeCyclicalFeaturesOperator`

2022-01-26 05:46 UTC, uabbas requested changes
Review comments are marked inline with code.

2022-01-27 05:59 UTC, abalhomaid commented on tasrif/processing_pipeline/custom/change_date_format_to_start_to_end.py
> +    >>> from tasrif.processing_pipeline.custom import ChangeDateFormatToStartToEnd
Thanks Ummar, I will address the comments during the upcoming weekend

2022-01-29 09:26 UTC, abalhomaid commented on tasrif/processing_pipeline/custom/change_date_format_to_start_to_end.py
> +                 aggregation_definition=None,
Good question. `aggregation_definition` parameter gives the user the ability to aggregate non-date columns.
In the example, the aggregation occurs in the `value` column
by summing the values and summing only the value of ones as shown below

`{'value': [np.sum, lambda x: x[x == 1].sum()]}`

```

2022-01-29 09:38 UTC, abalhomaid commented on tasrif/processing_pipeline/custom/change_date_format_to_start_to_end.py
> +    >>> from tasrif.processing_pipeline.custom import ChangeDateFormatToStartToEnd
Updated the repo accordingly

2022-01-30 05:13 UTC, uabbas requested changes

2022-01-30 05:13 UTC, uabbas commented on tasrif/processing_pipeline/custom/aggregate_activity_dates_operator.py
> +        """Creates a new instance of ChangeDateFormatToStartToEnd
Class name needs to be corrected.

2022-02-06 15:07 UTC, uabbas approved these changes

2022-02-06 15:07 UTC, merged